
name: LK Update - Cron Tweet

on:
  schedule:
    - cron:  "00 13 * * *"

jobs:
  tweet:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.7'

    - uses: actions/cache@v2
      with:
        path: ~/.cache/pip
        key: ${{ hashFiles('setup.py') }}-${{ hashFiles('dev-requirements.txt') }}

    - name: Test
      uses: nuuuwan/python-repo-test@v1

    - name: Tweet
      run: |
        export PYTHONPATH="$PYTHONPATH:./src"
        python src/covid19/tweet_lk_update.py --twtr_api_key "${{ secrets.TWTR_API_KEY}}" --twtr_api_secret_key "${{ secrets.TWTR_API_SECRET_KEY}}" --twtr_access_token "${{ secrets.TWTR_ACCESS_TOKEN}}" --twtr_access_token_secret "${{ secrets.TWTR_ACCESS_TOKEN_SECRET}}"
