
name: LK Vax Schedules - Cron Upload

on:
  schedule:
    - cron:  "0 3 * * *"

jobs:
  upload-data:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.7'

    - uses: actions/cache@v2
      with:
        path: ~/.cache/pip
        key: ${{ hashFiles('setup.py') }}-${{ hashFiles('dev-requirements.txt') }}

    - name: Install GhostScript
      run: sudo apt install ghostscript python3-tk

    - name: Test
      uses: nuuuwan/python-repo-test@v1

    - name: Run
      run: |
        export PYTHONPATH="$PYTHONPATH:./src"
        python src/covid19/lk_vax_schedule/scrape_vax_schedule.py --google_api_key "${{ secrets.google_api_key}}"

    - name: Checkout repo branch data
      uses: actions/checkout@v2
      with:
        ref: 'data'
        token: "${{ secrets.REPO_DATA_TOKEN }}"

    - name: Copy data, and push to repo branch data
      run: |
        git config --global user.email "${{ secrets.GIT_USER_EMAIL }}"
        git config --global user.name "${{ secrets.GIT_USER_NAME }}"
        cp -r /tmp/covid19.* .
        echo "* $(date)" >> update.log
        git add .
        git commit -m "Updated data $(date)"
        git push origin data
